# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(f"The present numpy version : {np.__version__} \n")
print(np.show_config())

The present numpy version : 1.20.3 

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/AnacondaPython\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/AnacondaPython\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/AnacondaPython\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/AnacondaPython\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/AnacondaPython\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/AnacondaPython\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/AnacondaPython\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/AnacondaPython\\Library\\include']
None


#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [4]:
x = np.array([1,2,3,4,5,6])
print(f"Size of the array: {x.size}")
print(f"Memory size of each array element in bytes: {x.itemsize}")
print(f"Memory size of array in bytes: {x.size * x.itemsize}")

Size of the array: 6
Memory size of each array element in bytes: 4
Memory size of array in bytes: 24


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
null_vector = np.zeros(10)
null_vector[4]=1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
x = np.arange(10)
print(f"Original array:{x}")
x = x[::-1]
print(f"Reverse array:{x}")

Original array:[0 1 2 3 4 5 6 7 8 9]
Reverse array:[9 8 7 6 5 4 3 2 1 0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
mat1= np.arange(0,9).reshape(3,3)
print(mat1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [15]:
elements= np.array([1,2,0,0,4,0])
non_zero = np.where(elements!=0)
print(non_zero)

#if want to find 0's index
zero = np.where(elements==0)
print(zero)

(array([0, 1, 4], dtype=int64),)
(array([2, 3, 5], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
identity_matrix=np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
from numpy.random import default_rng
rng = default_rng(1234)
random_array = rng.random((3,3,3))
random_array

array([[[0.97669977, 0.38019574, 0.92324623],
        [0.26169242, 0.31909706, 0.11809123],
        [0.24176629, 0.31853393, 0.96407925]],

       [[0.2636498 , 0.44100612, 0.60987081],
        [0.8636213 , 0.86375767, 0.67488131],
        [0.65987435, 0.7357577 , 0.22275366]],

       [[0.17206618, 0.87041497, 0.06013866],
        [0.68368891, 0.67123802, 0.61101798],
        [0.06013731, 0.97776927, 0.43895163]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [16]:
from numpy.random import default_rng
rng = default_rng(1234)
r_array = rng.random((10,10))
print(r_array)
print(f"\nMaximum value of the array : {r_array.max()}")
print(f"Minimum value of the array : {r_array.min()}")

[[0.97669977 0.38019574 0.92324623 0.26169242 0.31909706 0.11809123
  0.24176629 0.31853393 0.96407925 0.2636498 ]
 [0.44100612 0.60987081 0.8636213  0.86375767 0.67488131 0.65987435
  0.7357577  0.22275366 0.17206618 0.87041497]
 [0.06013866 0.68368891 0.67123802 0.61101798 0.06013731 0.97776927
  0.43895163 0.53259502 0.00313229 0.25126711]
 [0.85849044 0.42529835 0.73581899 0.92204322 0.15347417 0.99225923
  0.18233178 0.9401129  0.08688306 0.46821072]
 [0.8289892  0.28105226 0.86909151 0.97641657 0.84171366 0.4488736
  0.37050843 0.48266944 0.09218155 0.22668311]
 [0.53656624 0.73323165 0.44891079 0.30550077 0.9473596  0.75103384
  0.47204846 0.45727588 0.7463378  0.85539988]
 [0.29350156 0.7333145  0.8088307  0.88708697 0.02483321 0.51254945
  0.61278568 0.28034895 0.45213173 0.53122109]
 [0.98863456 0.00597817 0.20128829 0.2568758  0.34074484 0.05300196
  0.3264945  0.19835821 0.82921491 0.63712163]
 [0.08544074 0.22016044 0.68117601 0.13441009 0.95651369 0.13652398
  0.79770214 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [17]:
rng = default_rng(123)
r_array2 = rng.random((30))
print(r_array2)

print(f"\nMinimum value of the array : {r_array2.min()}")

[0.68235186 0.05382102 0.22035987 0.18437181 0.1759059  0.81209451
 0.923345   0.2765744  0.81975456 0.88989269 0.51297046 0.2449646
 0.8242416  0.21376296 0.74146705 0.6299402  0.92740726 0.23190819
 0.79912513 0.51816504 0.23155562 0.16590399 0.49778897 0.58272464
 0.18433799 0.01489492 0.47113323 0.72824333 0.91860049 0.62553401]

Minimum value of the array : 0.014894916760232246


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [20]:
border1_array = np.ones((5,5))
border1_array[1:-1,1:-1]=0
print(border1_array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [26]:
ar=np.arange(9).reshape(3,3)
print(f"A 2d array: ")
print(ar)
ar= np.pad(ar, pad_width=1,constant_values=0)
print(f"A 2d array with filled border with 0's: ")
print(ar)

A 2d array: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
A 2d array with filled border with 0's: 
[[0 0 0 0 0]
 [0 0 1 2 0]
 [0 3 4 5 0]
 [0 6 7 8 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [21]:
# np.nan is not a number or defined as missing value
print(f"Multiply with any value will give nan as output : {0 * np.nan}")
print(f"nan is not equal to another nan value , returns false : {np.nan == np.nan}")
print(f"inf defines positive infinity . there is no comparison between inf and nan ,return false : {np.inf > np.nan}")
print(f"subtraction will also be nan : {np.nan - np.nan}")
print(f"nanis inset nan . wil  return true :{np.nan in set([np.nan])}")
print(f"3*.1 will be 0.30000000000000004 , so not equal , return false : {0.3 == 3 * 0.1}")

Multiply with any value will give nan as output : nan
nan is not equal to another nan value , returns false : False
inf defines positive infinity . there is no comparison between inf and nan ,return false : False
subtraction will also be nan : nan
nanis inset nan . wil  return true :True
3*.1 will be 0.30000000000000004 , so not equal , return false : False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [34]:
mat=np.zeros((5,5))
mat= np.diag(np.arange(1,5),-1)
print (mat)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [41]:
chess=np.zeros((8,8))
chess[1:9:2, ::2] = 1
chess[::2, 1:9:2] = 1
chess

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [53]:
print (np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [44]:
arr= np.array([[0,1], [1,0]])
arr= np.tile(arr,(4,4))
print (arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [51]:
arr = np.random.random((5,5))
arr_max=arr.max() 
arr_min=arr.min()
arr = (arr-arr_min)/(arr_max-arr_min)
print (arr)

[[0.32744646 0.         0.82947489 0.69836364 0.81612955]
 [0.51684471 0.15147044 0.76190401 0.90025891 0.28592926]
 [0.16813845 0.41977744 0.72747002 0.27105336 0.18358758]
 [0.01099432 0.7776711  1.         0.10732928 0.39528795]
 [0.07954777 0.83574337 0.82549671 0.9883966  0.5817466 ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [58]:
color = np.dtype([("r", np.ubyte, 2),
                  ("g", np.ubyte, 3),
                  ("b", np.ubyte, 4),
                  ("a", np.ubyte, 5)])
print(color)

[('r', 'u1', (2,)), ('g', 'u1', (3,)), ('b', 'u1', (4,)), ('a', 'u1', (5,))]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [52]:
a=np.arange(15).reshape(5,3)
b=np.arange(6).reshape(3,2)
c=np.dot(a, b)
print (c)

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [65]:
a = np.arange(15)
print("Before negation")
print(a)
a[(3 < a) & (a < 8)] = 0
print("After negation")
print(a)

Before negation
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
After negation
[ 0  1  2  3  0  0  0  0  8  9 10 11 12 13 14]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [1]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [9]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\isfakul\AppData\Local\Temp/ipykernel_4460/3912170336.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
C:\Users\isfakul\AppData\Local\Temp/ipykernel_4460/3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

In [22]:
Z1 = np.array([4,2,7,8,19,18,20,1,9])
print(Z1)
Z2 = np.array([0,1,2,3,4,8,9,12,13])
print(Z2)
print(np.intersect1d(Z1,Z2))

[ 4  2  7  8 19 18 20  1  9]
[ 0  1  2  3  4  8  9 12 13]
[1 2 4 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [10]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\isfakul\AppData\Local\Temp/ipykernel_4460/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [24]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday)
print(today)
print(tomorrow)

2022-10-12
2022-10-13
2022-10-14


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [34]:
Z = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [31]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
print("Keeping A+B in B")
print(B)
np.divide(A,2,out=A)
np.negative(A,out=A)
print("keeping (-A/2) in A")
print(A)
np.multiply(A,B,out=A)
print(A)

Keeping A+B in B
[3. 3. 3.]
keeping (-A/2) in A
[-0.5 -0.5 -0.5]
[-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [37]:
a=np.ones((5,5))
b=np.array([0,1,2,3,4])
np.multiply(a,b,out=a)

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [39]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [44]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [48]:
a=np.random.random(10)
print("before sort:")
print(a)
a.sort()
print("after sort:")
print(a)

before sort:
[0.06575052 0.57006953 0.85395565 0.140397   0.71627094 0.39825783
 0.17185713 0.18965107 0.29356315 0.81528457]
after sort:
[0.06575052 0.140397   0.17185713 0.18965107 0.29356315 0.39825783
 0.57006953 0.71627094 0.81528457 0.85395565]


#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [52]:
a=np.random.random((10,2))
print(a)
x=a[:,0]
y=a[:,1]
R=np.sqrt(x**2+y**2)
T=np.arctan2(y,x)
print(R)
print(T)

[[0.42537083 0.57857625]
 [0.77800295 0.03184043]
 [0.85841962 0.0618248 ]
 [0.98148689 0.3713715 ]
 [0.73983152 0.27215435]
 [0.71916146 0.48577386]
 [0.21989685 0.73562449]
 [0.8760879  0.29777266]
 [0.44526744 0.95940754]
 [0.62534149 0.02424833]]
[0.71811617 0.77865422 0.86064311 1.04939664 0.78830113 0.86785336
 0.76778774 0.92530998 1.0576984  0.62581144]
[0.93683294 0.04090302 0.07189751 0.36172754 0.35249621 0.59407426
 1.28032568 0.32763903 1.13627341 0.03875672]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [56]:
a=random.random(10)
print(a)
a[a.argmax()]=0
print(a)

[0.3387826  0.70972616 0.06428731 0.95189531 0.4942742  0.98069041
 0.34972087 0.07427819 0.36404755 0.14744098]
[0.3387826  0.70972616 0.06428731 0.95189531 0.4942742  0.
 0.34972087 0.07427819 0.36404755 0.14744098]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [61]:
print("Int data type")
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
    
print("\nFloat data type")
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)

Int data type
-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807

Float data type
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)